on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Releasing diglett
    runs-on: ubuntu-latest
    steps:
      - name: Prepare
        run: |
          sudo apt-get update
          sudo apt-get install musl-dev musl-tools
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        name: Install toolchain
        with:
          toolchain: stable
          target: x86_64-unknown-linux-musl
      - uses: actions-rs/cargo@v1
        name: Build release
        with:
          command: build
          args: |
            --release
            --target=x86_64-unknown-linux-musl
      - name: Strip
        run: |
          strip target/x86_64-unknown-linux-musl/release/diglett
          strip target/x86_64-unknown-linux-musl/release/diglett-server
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            target/x86_64-unknown-linux-musl/release/diglett
            target/x86_64-unknown-linux-musl/release/diglett-server
